{% set name = "bilby_pipe" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 517285ed9277b6e61329b8144253e4117484bf6b039c31b08cb7ba2cbfa22cc6

build:
  entry_points:
    - bilby_pipe = bilby_pipe.main:main
    - bilby_pipe_generation = bilby_pipe.data_generation:main
    - bilby_pipe_analysis = bilby_pipe.data_analysis:main
    - bilby_pipe_create_injection_file = bilby_pipe.create_injections:main
    - bilby_pipe_xml_converter = bilby_pipe.xml_converter:main
    - bilby_pipe_pp_test = bilby_pipe.pp_test:main
    - bilby_pipe_review = bilby_pipe.review:main
    - bilby_pipe_plot = bilby_pipe.plot:main
    - bilby_pipe_plot_calibration = bilby_pipe.plot:plot_calibration
    - bilby_pipe_plot_corner = bilby_pipe.plot:plot_corner
    - bilby_pipe_plot_marginal = bilby_pipe.plot:plot_marginal
    - bilby_pipe_plot_skymap = bilby_pipe.plot:plot_skymap
    - bilby_pipe_plot_waveform = bilby_pipe.plot:plot_waveform
    - bilby_pipe_gracedb = bilby_pipe.gracedb:main
    - bilby_pipe_write_default_ini = bilby_pipe.parser:main
    - bilby_pipe_process_mcmc = bilby_pipe.process_bilby_mcmc:main
    - bilby_pipe_htcondor_sync = bilby_pipe.htcondor_sync:main
    - bilby_pipe_to_ligo_skymap_samples = bilby_pipe.ligo_skymap:main
    - bilby_pipe_reweight_result = bilby_pipe.data_analysis:reweight
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=3.4.3
  run:
    - astropy
    - bilby >=2.1.2
    - configargparse
    - corner
    - dynesty >=1.0.0
    - future
    - gwosc
    - gwpy >=3.0.4
    - jinja2
    - ligo-gracedb
    - matplotlib-base
    - numpy
    - pesummary >=0.13.10
    - plotly
    - pycondor >=0.6
    - python >=3.9
    - python-ldas-tools-framecpp
    - python-ligo-lw >=1.8.0
    - python-nds2-client
    - scipy >=1.2.0
    - seaborn
    - tqdm
    # for bilby[gw]
    - astropy >=5
    - pyfftw
    - pytables
    - python-lal
    - python-lalsimulation

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check bilby_pipe
    - python -m pip show bilby_pipe
    # check entry points
    - bilby_pipe --help
    - bilby_pipe_generation --help
    - bilby_pipe_analysis --help
    - bilby_pipe_create_injection_file --help
    - bilby_pipe_xml_converter --help
    - bilby_pipe_pp_test --help
    - bilby_pipe_review --help
    - bilby_pipe_plot --help
    - bilby_pipe_plot_calibration --help
    - bilby_pipe_plot_corner --help
    - bilby_pipe_plot_marginal --help
    - bilby_pipe_plot_skymap --help
    - bilby_pipe_plot_waveform --help
    - bilby_pipe_gracedb --help
    - bilby_pipe_write_default_ini --help
    - bilby_pipe_process_mcmc --help
    - bilby_pipe_htcondor_sync --help
    - bilby_pipe_to_ligo_skymap_samples --help
    - bilby_pipe_reweight_result --help

about:
  home: https://lscsoft.docs.ligo.org/bilby_pipe/
  doc_url: https://lscsoft.docs.ligo.org/bilby_pipe/
  dev_url: https://git.ligo.org/lscsoft/bilby_pipe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automating the running of bilby for gravitational wave signals
  description: |
    A package for automating transient gravitational wave parameter estimation

extra:
  recipe-maintainers:
    - ColmTalbot
    - duncanmmacleod
    - GregoryAshton
