{% set name = "bilby_pipe" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae69aa2853205aec195d78654e0ccbba875d19f599983d896baf47ed1d49afb8

build:
  number: 0
  noarch: python
  entry_points:
    - bilby_pipe = bilby_pipe.main:main
    - bilby_pipe_generation = bilby_pipe.data_generation:main
    - bilby_pipe_analysis = bilby_pipe.data_analysis:main
    - bilby_pipe_create_injection_file = bilby_pipe.create_injections:main
    - bilby_pipe_pp_test = bilby_pipe.pp_test:main
    - bilby_pipe_plot = bilby_pipe.plot:main
    - bilby_pipe_gracedb = bilby_pipe.gracedb:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - bilby >=0.5.2
    - configargparse
    - future
    - gwpy
    - ligo-gracedb
    - matplotlib-base
    - numpy
    - pesummary
    - pycondor >=0.5
    - python >=3.5
    - scipy >=1.2.0
    - tqdm
    - python-ldas-tools-framecpp
    - python-nds2-client

test:
  imports:
    - bilby_pipe
  commands:
    - bilby_pipe --help
    - bilby_pipe_generation --help
    - bilby_pipe_analysis --help
    - bilby_pipe_create_injection_file --help
    - bilby_pipe_pp_test --help
    - bilby_pipe_plot --help
    - bilby_pipe_gracedb --help

about:
  home: https://lscsoft.docs.ligo.org/bilby_pipe/
  doc_url: https://lscsoft.docs.ligo.org/bilby_pipe/
  dev_url: https://git.ligo.org/lscsoft/bilby_pipe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automating the running of bilby for gravitational wave signals
  description: |
    A package for automating transient gravitational wave parameter estimation

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
