{% set name = "bilby_pipe" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c7e33a25540c3a99bd8f878bbe5d58911f29d55b54bdfbf8e49213dcc0592fb

build:
  entry_points:
    - bilby_pipe = bilby_pipe.main:main
    - bilby_pipe_analysis = bilby_pipe.data_analysis:main
    - bilby_pipe_create_injection_file = bilby_pipe.create_injections:main
    - bilby_pipe_generation = bilby_pipe.data_generation:main
    - bilby_pipe_gracedb = bilby_pipe.gracedb:main
    - bilby_pipe_plot = bilby_pipe.plot:main
    - bilby_pipe_plot_calibration = bilby_pipe.plot:plot_calibration
    - bilby_pipe_plot_corner = bilby_pipe.plot:plot_corner
    - bilby_pipe_plot_marginal = bilby_pipe.plot:plot_marginal
    - bilby_pipe_plot_skymap = bilby_pipe.plot:plot_skymap
    - bilby_pipe_plot_waveform = bilby_pipe.plot:plot_waveform
    - bilby_pipe_pp_test = bilby_pipe.pp_test:main
    - bilby_pipe_review = bilby_pipe.review:main
    - bilby_pipe_write_default_ini = bilby_pipe.parser:main
    - bilby_pipe_xml_converter = bilby_pipe.xml_converter:main
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - bilby >=1.0.0
    - configargparse
    - dynesty >=1.0.0
    - future
    - gwpy
    - jinja2
    - ligo-gracedb
    - matplotlib-base
    - numpy
    - pesummary >=0.2.4
    - pycondor >=0.5
    - python >=3.5
    - python-ldas-tools-framecpp
    - python-nds2-client
    - scipy >=1.2.0
    - tqdm

test:
  imports:
    - bilby_pipe
  requires:
    # for bilby_pipe_xml_converter
    - python-ligo-lw
  commands:
    - bilby_pipe --help
    - bilby_pipe_analysis --help
    - bilby_pipe_create_injection_file --help
    - bilby_pipe_generation --help
    - bilby_pipe_gracedb --help
    - bilby_pipe_plot --help
    - bilby_pipe_plot_calibration --help
    - bilby_pipe_plot_corner --help
    - bilby_pipe_plot_marginal --help
    - bilby_pipe_plot_skymap --help
    - bilby_pipe_plot_waveform --help
    - bilby_pipe_pp_test --help
    - bilby_pipe_review --help
    - bilby_pipe_write_default_ini --help
    - bilby_pipe_xml_converter --help

about:
  home: https://lscsoft.docs.ligo.org/bilby_pipe/
  doc_url: https://lscsoft.docs.ligo.org/bilby_pipe/
  dev_url: https://git.ligo.org/lscsoft/bilby_pipe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automating the running of bilby for gravitational wave signals
  description: |
    A package for automating transient gravitational wave parameter estimation

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
